config/routes.rb
Rails.application.routes.draw do
  
  root 'welcome#index'

  resources :blogs  do
    member do
      get 'waiting'
      get 'position_in_queue'
    end
  end

  post 'query/search' => 'query#search', as: :search

end

app/models/Query.rb
class Query
  include ActiveAttr::Model
  attr_accessor :query, :structure, :blog_url, :api_url, :post_types, :number_of_posts, :show_reblogs
  validates :structure, :inclusion => { :in => %w{standard custom}, :message => "Only normal and custom URI structures are allowed" }
  validates :query, presence: { :message => "Search field is empty"}
  validate :validate_post_types

  #Checks if user has sent valid post types
  def validate_post_types
    if !post_types.is_a?(Array) || post_types.detect{ |a| !AVAILABLE_TYPES.include?(a) }
      errors.add(:post_types, "You must select a post type")
    end
  end

  #Returns true if blog url leads to a valid blog, otherwise returns false
  #Check if query is valid before executing this method
  def does_blog_exist?
    query.downcase!
    structure.downcase!
    if structure == "standard"
      self.query = query + ".tumblr.com"
    elsif structure == "custom"
      self.query = "http://" + query
      #Must check if uri is valid before calling the format uri method
      if is_uri_valid? query
        self.query = format_uri (query)
      else
        errors.add(:query, "Invalid URL")
        return false
      end
    end

    self.api_url = "http://api.tumblr.com/v2/blog/#{query}/info"
    if is_uri_valid? api_url
      myClient = Tumblr::Client.new
      response = myClient.get(api_url)

      #If blog is found, then "blog" key will be present
      if response["blog"].present?
        self.number_of_posts = response["blog"]["posts"]
        return true
      else
        errors.add(:query, "Blog could not be found")
        return false
      end
    else
      errors.add(:query, "Invalid blog name")
      return false
    end
    
  end

  private
    #Returns a blog link that is compatible with the Tumblr API.
    #must call is_uri_valid? on the uri prior to calling this method
    def format_uri (uri)
      uri = URI.parse(uri)
      if(uri.scheme)
        uri.host
      else
        uri.to_s
      end
    end

    #http://stackoverflow.com/questions/5331014/check-if-given-string-is-an-url
    def is_uri_valid?(string)
      uri = URI.parse(string)
      %w( http https ).include?(uri.scheme)
    rescue URI::BadURIError
      false
    rescue URI::InvalidURIError
      false
    end

end

app/models/blog.rb
class Blog < ActiveRecord::Base 
  serialize :posts, Array
  serialize :post_types, Array

  #Creates a new job that retrieves the blog's posts 
  def get_posts (number_of_posts)
    @job = Delayed::Job.enqueue BlogJob.new(self.id, number_of_posts)
    self.update(job_id: @job.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
	before_action :set_blog, only: [:show, :waiting, :position_in_queue]
  
  def show
  end

  #Renders the job's position within the queue, in plain text
  def position_in_queue
  	rank = Delayed::Job.all.order(id: :asc).pluck(:id).index(@blog.job_id)
  	render plain: rank
  end

  #shows waiting page as job executes
  def waiting
    #In case user navigates to waiting page and job is already complete, direct them to show page
    unless @blog.posts.blank? && Delayed::Job.find_by(id: @blog.job_id) != nil
      redirect_to @blog
    end
  end

  private
    def set_blog
    	@blog = Blog.find(params[:id])
    end
end

app/controllers/query_controller.rb
class QueryController < ApplicationController

  #Creates a new query variable containing user parameters.
  # If query is valid, job is created. If invalid, user redirected to home page and shown errors.
  def search
    q = Query.new(query: params[:search], structure: params[:structure], post_types: params[:post_types], show_reblogs: params[:show_reblogs])
    if q.valid? && q.does_blog_exist?
      blog = Blog.create(name: q.query, post_types: q.post_types, reblogs: q.show_reblogs)
      blog.get_posts(q.number_of_posts)
      redirect_to waiting_blog_path(blog)
      return
    else
      error_message = ""
      q.errors.each do |attr, msg|
        error_message += msg + " "
      end
      flash[:danger] = error_message
      #Remember search parameters so user doesn't need to reenter them
      redirect_to :controller => 'welcome', :action => 'index', :uri_structure => params[:structure], :post_type => params[:post_type], :show_reblogs => params[:show_reblogs], :post_types => params[:post_types]
    end
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  #Renders the posts depending on post type. Used in the show blog page
  def post_renderer(post)
    post_type = post["type"]
    case post_type
    when 'photo'
      short_url_block(post){ content_tag :img, nil, src: post["photos"][0]["alt_sizes"][2]["url"] }
    when 'text'
      if post["title"].present? 
        short_url_block(post){ post["title"] }
      else
        short_url_block(post){"link to text post"}
      end
    when 'video'
      if post["thumbnail_url"].present?
        short_url_block(post){ content_tag :img, nil, src: post["thumbnail_url"] }
      else
        short_url_block(post){ "link to video post" }
      end
    when 'audio'
      if post["thumbnail_url"].present?
        short_url_block(post){ content_tag :img, nil, src: post["album_art"] }
      else
        short_url_block(post){ "link to audio post" }
      end
    when 'quote'
      short_url_block(post){ post["text"] }
    when 'link'
      short_url_block(post){ post["title"] }
    when 'chat'
      if post["title"].present?
        short_url_block(post){ content_tag :h5, post["title"] }
      else
        short_url_block(post){ "link to chat post" }
      end
    when 'answer'
      short_url_block(post){ content_tag :h5, post["question"] }
    end
  end

  def short_url_block (post)
    content_tag :a, href: post["short_url"], target: "_blank" do 
      yield
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blogs/show.html.erb
<%= render 'layouts/search' %>
<div class="page-header">
  <h1><%= link_to @blog.name, "http://#{@blog.name}", target: "_blank" %>
    <small class='text-uppercase'><%= @blog.post_types.join " : " %><% unless @blog.reblogs %> : NO REBLOGS<% end %></small>
  </h1>
</div>

<% if @blog.posts.present? %>
  <table class="table">
  <caption>TOP 30</caption>
    <tr>
      <th class="col-xs-1">Rank</th>
      <th class="col-xs-1">Notes</th>
      <th class="col-xs-8">Post</th>
      <th class="col-xs-1">Type</th>
      <th class="col-xs-1">Date</th>
    </tr>

    <%= render partial: 'layouts/blog', object: @blog.posts %>
    
  </table>
<% end %>

app/views/blogs/waiting.html.erb
<script type="text/javascript">
	 
	var interval = setInterval(function(){
    $.ajax({
        url: '/progress-job/' + <%= @blog.job_id %>,
        success: function(job){

          var stage, progress;
          progress = Math.floor(job.progress_current / job.progress_max * 100);
          stage = job.progress_stage;

          // In job stage
  	    	if (progress !== 0 && stage != null){
  	    		$('.progress-status').text(stage);
            $('.progress-bar').css('width', progress + '%').text(progress + '%');
  	    	}
  	    	
        },
        error: function(){
        	
          // Job is no loger in database which means it finished successfuly
          $('.progress-bar').removeClass("progress-bar-info").addClass("progress-bar-success").css('width', '100%').text('100%');
          $('.progress-status').removeClass("text-info").addClass("text-success").text('Successful! Redirecting now...');
          clearInterval(interval);
          window.location.href = '<%= url_for(@blog) %>';
        }
    })
    $.ajax("<%= position_in_queue_blog_path(@blog) %>")
	 	   .done(function(number){
	 		  $('#queue-number').text(number);
    });
  },1000);


</script>
<div class="page-header">
  <h3>Position in queue: <span id="queue-number" class="label label-info"></span></h3>
</div>
  
<div class="well">
  <div class="progress-status text-info">Please be patient...</div>
  <div class="progress">
    <div class="progress-bar progress-bar-info col-xs-12" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="min-width: 2.5em;">0.00%</div>
  </div>
</div>
<p class="bg-info" style="padding:15px;border-radius:5px;">*This operation may not take as long as indicated, depending on the type of post you wanted filtered. If you chose all post types, then all of this blog's posts will be processed.</p>

app/views/layouts/_blog.html.erb
<% @blog.posts.each_with_index do |post, index|%>
  <tr>
    <td><%= index + 1 %></td>
    <td><%= post["note_count"] %></td>
    <td class="center">
      <%= post_renderer(post) %>
    </td>
    <td><%= post["type"].capitalize %></td>
    <td><%= Time.at(post["timestamp"]).strftime('%m/%d/%Y') %></td>
  </tr>
<% end %>

app/views/layouts/_search.html.erb
<script type="text/javascript">
$(document).ready(function() {

  $("#name-radio").click(function() {
    $("#search").prop("placeholder", "willitbeard");
    $("#tumblr-addon").show();
  });

  $("#url-radio").click(function() {
    $("#search").prop("placeholder", "haiku.nytimes.com");
    $("#tumblr-addon").hide();
  });


  //Makes sure textbox type is set properly depending on last search
  if ($("#name-radio").prop("checked")) {
    $("#name-radio").click();
  } else {
    $("#url-radio").click();
  }

  $('[data-toggle="popover"]').popover()


  //http://stackoverflow.com/questions/18147338/twitter-bootstrap-3-0-icon-change-on-collapse
  $('#options-box').on('shown.bs.collapse', function() {
    $("#options-button span").removeClass("glyphicon glyphicon-chevron-down").addClass("glyphicon glyphicon-chevron-up");
  });

  $('#options-box').on('hidden.bs.collapse', function() {
    $("#options-button span").removeClass("glyphicon glyphicon-chevron-up").addClass("glyphicon glyphicon-chevron-down");
  });

  //prevent URL option from being selected when question mark is clicked
  $("#url-question").click(function(event){event.preventDefault();})

});
</script>
<div style="margin-top:20px;">
<%= form_tag(search_url, method: "post") do %>
  <div class="form-group">
    <div class="input-group">
      <div class="input-group-addon">http://</div>
      <%= text_field_tag(:search, nil, :placeholder => "e.g. willitbeard", class: "form-control")%>
        <div id="tumblr-addon" class="input-group-addon">.tumblr.com</div>
    </div>
  </div>
  <button type="submit" id="search-button" title="search" class="btn btn-primary col-xs-12">
    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
  </button>
  <div class="center">
    <button id="options-button" class="btn btn-link" type="button" data-toggle="collapse" data-target="#options-box" aria-expanded="false">
      <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span>
    </button>
  </div>
  <div id="options-box" class="collapse panel panel-primary">
    <div class="panel-body">
      <div class="form-group">
        <label class="radio-inline">
          <input type="radio" id="name-radio" name="structure" value="standard" checked="checked"> Name
        </label>
        <label class="radio-inline">
          <input type="radio" id="url-radio" name="structure" value="custom"
          <% if params[:uri_structure] == "custom" %> checked="checked"
          <% end %>
            > URL
            <a tabindex="0" role="button" data-toggle="popover" data-content="Use this for blogs that don't end with .tumblr.com"
             data-trigger="hover focus" data-placement="bottom">
              <span id="url-question" class="glyphicon glyphicon-question-sign" aria-hidden="true" ></span>
            </a>
        </label>
        <label class="checkbox-inline">
          <input type="checkbox" name="show_reblogs" value="true"
          <% if params[:show_reblogs] %> checked="checked"<% end %>
          > Reblogs?
        </label>
      </div>
      <div class="form-group">
        <%= select_tag "post_types", options_for_select(AVAILABLE_TYPES.collect { |a| [a.capitalize, a] },
         params[:post_types].present? ? params[:post_types] : "photo"),
          multiple:true, class:"form-control" %>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Get Top 30 Tumblr Posts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--For Bootstrap mobile -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
<div class="container">
<%= yield %>
</div>
</body>

<footer class="footer">
  <div class="container">
    <p class="center"><a href="https://github.com/a-parallelogram/tumblrtop30" target="_blank" class="btn btn-default" role="button">Check me out on GitHub!<%= image_tag "Octocat.png", width: "30px", height: "30px", alt: ":Octocat:" %></a></p>
    <p class="center small">This application uses the Tumblr application programming interface but is not endorsed or certified by Tumblr, Inc. All of the Tumblr logos and trademarks displayed on this application are the property of Tumblr, Inc.</p>
  </div>
</footer>
</html>

app/views/welcome/index.html.erb
<script>
$(document).ready(function(){
  //open options panel for this page
  $("#options-button").click();
})

</script>

<div class="page-header">
  <h2 class="center">Find your most popular <a href="https://www.tumblr.com/" target="_blank"><%= image_tag("tumblr_logotype_blue_transparent_128.png", alt: "Tumblr logo") %></a> posts</br>
  <small>Enter the name or URL of a Tumblr blog to retrieve its top posts</small>
  </h2>
</div>

<%= render 'layouts/search' %>